apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-1
  template:
    metadata:
      labels:
        app: microservice-1
    spec:
      containers:
        - name: node-app
          image: shrimanwar92/node-app-elk:2.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: local-tmp-log-location
              mountPath: /tmp/logs
            - name: filebeat-config
              mountPath: /etc/filebeat
      volumes:
        - name: local-tmp-log-location
          persistentVolumeClaim:
            claimName: test-pvc
        - name: filebeat-config
          configMap:
            name: filebeat-config-file
      nodeSelector:
        node: app

---

apiVersion: v1
kind: Service
metadata:
  name: microservice-1-deployment-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: microservice-1

