apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-file
data:
  filebeat.yml: |
    setup.ilm.enabled: false
    setup.template.name: "app-log"
    setup.template.pattern: "app-log-*"

    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /tmp/logs/*.log

    output.elasticsearch:
      hosts: ["http://192.168.49.2:31026"]
      path: "/es/"
      index: "app-log-%{+yyyy.MM.dd}"
      username: "admin"
      password: "admin"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: create-log-folder
data:
  create-log-folder.sh: |
    #!/bin/bash
    mkdir -p /tmp/logs